export enum netZeroFactors {


    //investee's sector
    TELECOMMUNICATION = 'TELECOMMUNICATION',
    APPAREL = 'APPAREL',
    ENERGY_GENERATION = 'ENERGY_GENERATION',
    FOOD_AND_BEVERAGE = 'FOOD_AND_BEVERAGE',

    // construction sector
    RESIDENTIAL = 'RESIDENTIAL',
    COMMERCIAL = 'COMMERCIAL',
    HEALTH_CARE_STRUCTURES = 'HEALTH_CARE_STRUCTURES',

    //operating sector    
    POWER_GENERATION_AND_SUPPLY = 'POWER_GENERATION_AND_SUPPLY',
    PAPER_MILLS = 'PAPER_MILLS',


    //upstream EFs
    DIESEL_UPSTREAM = 'DIESEL_UPSTREAM',
    PETROL_UPSTREAM = 'PETROL_UPSTREAM',
    ELECTRICITY_UPSTREAM = 'ELECTRICITY_UPSTREAM',
    STEAM_UPSTREAM = 'STEAM_UPSTREAM',
    HEATING_UPSTREAM = 'HEATING_UPSTREAM',
    COOLING_UPSTREAM = 'COOLING_UPSTREAM',

    //Life cycle EFs
    DIESEL_LC = 'DIESEL_LC',
    PETROL_LC = 'PETROL_LC',
    ELECTRICITY_LC = 'ELECTRICITY_LC',
    STEAM_LC = 'STEAM_LC',
    HEATING_LC = 'HEATING_LC',
    COOLING_LC = 'COOLING_LC',
    //bussiness travel

    HOTEL_FACTOR = 'HOTEL_FACTOR',
    EEIO_EMISSION_FACTORS_VAN = 'EEIO_EMISSION_FACTORS_VAN',
    EEIO_EMISSION_FACTORS_JEEP = 'EEIO_EMISSION_FACTORS_JEEP',
    EEIO_EMISSION_FACTORS_CAR = 'EEIO_EMISSION_FACTORS_CAR',
    EEIO_EMISSION_FACTORS_PRIME_MOVE = 'EEIO_EMISSION_FACTORS_PRIME_MOVE',
    EEIO_EMISSION_FACTORS_BIKE = 'EEIO_EMISSION_FACTORS_BIKE',
    EEIO_EMISSION_FACTORS_THREEWHEEL = 'EEIO_EMISSION_FACTORS_THREEWHEEL',
    EEIO_EMISSION_FACTORS_VAN_DIESEL = 'EEIO_EMISSION_FACTORS_VAN_DIESEL',
    EEIO_EMISSION_FACTORS_MEDIUM_BUS_DIESEL = 'EEIO_EMISSION_FACTORS_MEDIUM_BUS_DIESEL',
    EEIO_EMISSION_FACTORS_BUS_DIESEL = 'EEIO_EMISSION_FACTORS_BUS_DIESEL',
    EEIO_EMISSION_FACTORS_RAILWAY = 'EEIO_EMISSION_FACTORS_RAILWAY',
    EEIO_EMISSION_FACTORS_NONE = 'EEIO_EMISSION_FACTORS_NONE',

    //employee commuting

    ENERGY_FACTOR = 'ENERGY_FACTOR',


    //process of sold products
    TEA_PACKETS = 'TEA_PACKETS',
    FABRIC = 'FABRIC',
    CLOTHES = 'CLOTHES',

    //upstream Leased Assets
    FOOD_OUTLET = 'FOOD_OUTLET',
    CLOTHING_OUTLET = 'CLOTHING_OUTLET',


    //up-down stream transport
    AIR_LONG_HAUL = 'AIR_LONG_HAUL',
    TRUCK_RIGID = 'TRUCK_RIGID',
    CONTAINER_2000_2999_TEU = 'CONTAINER_2000_2999_TEU',
    DISTRIBUTION_CENTER = 'DISTRIBUTION_CENTER',
    SUPERMARKETS = 'SUPERMARKETS',








    // //Purchase_good_and_services
    // SUPPLIER_SPECIFIC_PRODUCT_CEMENT = 'SUPPLIER_SPECIFIC_PRODUCT_CEMENT',
    // SUPPLIER_SPECIFIC_PRODUCT_PAINT = 'SUPPLIER_SPECIFIC_PRODUCT_PAINT',
    // SUPPLIER_SPECIFIC_PRODUCT_TIMBER = 'SUPPLIER_SPECIFIC_PRODUCT_TIMBER',
    // SUPPLIER_SPECIFIC_PRODUCT_TEA = 'SUPPLIER_SPECIFIC_PRODUCT_TEA',
    // SUPPLIER_SPECIFIC_PRODUCT_FABRIC = 'SUPPLIER_SPECIFIC_PRODUCT_FABRIC',

    CRADLE_TO_GATE_EF_COTTON = 'CRADLE_TO_GATE_EF_COTTON',
    CRADLE_TO_GATE_EF_POLYMER = 'CRADLE_TO_GATE_EF_POLYMER',
    CRADLE_TO_GATE_EF_CHEMICAL__A = 'CRADLE_TO_GATE_EF_CHEMICALA',
    CRADLE_TO_GATE_EF_PREPROCESSED_TEA = 'CRADLE_TO_GATE_EF_PRE_PROCESSED_TEA',
    CRADLE_TO_GATE_EF_LOW_DENSITY_POLYETHYLENE = 'CRADLE_TO_GATE_EF_LOW_DENSITY_POLYETHYLENE',

    CRADLE_TO_GATE_EF_VEHICLE_LORRY = 'CRADLE_TO_GATE_EF_VEHICLE_LORRY',
    CRADLE_TO_GATE_EF_VEHICLE_TRACTOR = 'CRADLE_TO_GATE_EF_VEHICLE_TRACTOR',
    CRADLE_TO_GATE_EF_VEHICLE_VAN = 'CRADLE_TO_GATE_EF_VEHICLE_VAN',

    // AVERAGE_METHOD_EF_PER_UNIT_OF_MASS_GLASS = 'AVERAGE_METHOD_EF_PER_UNIT_OF_MASS_GLASS',
    // AVERAGE_METHOD_EF_PER_UNIT_OF_MASS_ALUMINIUM = 'AVERAGE_METHOD_EF_PER_UNIT_OF_MASS_ALUMINIUM',
    // AVERAGE_METHOD_EF_PER_UNIT_OF_MASS_BATTERY = 'AVERAGE_METHOD_EF_PER_UNIT_OF_MASS_BATTERY',
    // AVERAGE_METHOD_EF_PER_UNIT_OF_MASS_PRE_PROCESSED_TEA = 'AVERAGE_METHOD_EF_PER_UNIT_OF_MASS_PRE_PROCESSED_TEA',
    // AVERAGE_METHOD_EF_PER_UNIT_OF_MASS_THREAD = 'AVERAGE_METHOD_EF_PER_UNIT_OF_MASS_THREAD',
    // AVERAGE_METHOD_EF_PER_REFERENCE_UNIT_GLASS = 'AVERAGE_METHOD_EF_PER_REFERENCE_UNIT_GLASS',
    // AVERAGE_METHOD_EF_PER_REFERENCE_UNIT_ALUMINIUM = 'AVERAGE_METHOD_EF_PER_REFERENCE_UNIT_ALUMINIUM',
    // AVERAGE_METHOD_EF_PER_REFERENCE_UNIT_BATTERY = 'AVERAGE_METHOD_EF_PER_REFERENCE_UNIT_BATTERY ',
    // AVERAGE_METHOD_EF_PER_REFERENCE_UNIT_PRE_PROCESSED_TEA = 'AVERAGE_METHOD_EF_PER_REFERENCE_UNIT_PRE_PROCESSED_TEA',
    // AVERAGE_METHOD_EF_PER_REFERENCE_UNIT_THREAD = 'AVERAGE_METHOD_EF_PER_REFERENCE_UNIT_THREAD',

    // SPEND_BASED_METHOD_EF_STEEL = 'SPEND_BASED_METHOD_EF_STEEL',
    // SPEND_BASED_METHOD_EF_ALUMINIUM = 'SPEND_BASED_METHOD_EF_ALUMINIUM',
    // SPEND_BASED_METHOD_EF_PET = 'SPEND_BASED_METHOD_EF_PET',
    // SPEND_BASED_METHOD_EF_EPOXY_RESIN = 'SPEND_BASED_METHOD_EF_EPOXY_RESIN',
    // SPEND_BASED_METHOD_EF_COPPER = 'SPEND_BASED_METHOD_EF_COPPER',
    // SPEND_BASED_METHOD_EF_GLASS = 'SPEND_BASED_METHOD_EF_GLASS',



     //Purchase_good_and_services
     SUPPLIER_SPECIFIC_PRODUCT_CEMENT = 'SUPPLIER_SPECIFIC_PRODUCT_CEMENT',
     SUPPLIER_SPECIFIC_PRODUCT_PAINT = 'SUPPLIER_SPECIFIC_PRODUCT_PAINT',
     SUPPLIER_SPECIFIC_PRODUCT_TIMBER = 'SUPPLIER_SPECIFIC_PRODUCT_TIMBER',
     SUPPLIER_SPECIFIC_PRODUCT_TEA = 'SUPPLIER_SPECIFIC_PRODUCT_TEA',
     SUPPLIER_SPECIFIC_PRODUCT_FABRIC = 'SUPPLIER_SPECIFIC_PRODUCT_FABRIC',
 
     CRADLE_TO_GATE_EF_COTTON_KG = 'CRADLE_TO_GATE_EF_COTTON_KG',
     CRADLE_TO_GATE_EF_POLYMER_KG = 'CRADLE_TO_GATE_EF_POLYMER_KG',
     CRADLE_TO_GATE_EF_CHEMICAL_A_KG = 'CRADLE_TO_GATE_EF_CHEMICAL_A_KG',
     CRADLE_TO_GATE_EF_PREPROCESSED_TEA_KG = 'CRADLE_TO_GATE_EF_PRE_PROCESSED_TEA_KG',
     CRADLE_TO_GATE_EF_LOW_DENSITY_POLYETHYLENE_KG = 'CRADLE_TO_GATE_EF_LOW_DENSITY_POLYETHYLENE_KG',
     CRADLE_TO_GATE_EF_COTTON_UNIT = 'CRADLE_TO_GATE_EF_COTTON_UNIT',
     CRADLE_TO_GATE_EF_POLYMER_UNIT = 'CRADLE_TO_GATE_EF_POLYMER_UNIT',
     CRADLE_TO_GATE_EF_CHEMICAL__A_UNIT= 'CRADLE_TO_GATE_EF_CHEMICALA_UNIT',
     CRADLE_TO_GATE_EF_PREPROCESSED_TEA_UNIT = 'CRADLE_TO_GATE_EF_PRE_PROCESSED_TEA_UNIT',
     CRADLE_TO_GATE_EF_LOW_DENSITY_POLYETHYLENE_UNIT = 'CRADLE_TO_GATE_EF_LOW_DENSITY_POLYETHYLENE_UNIT',
 
     CRADLE_TO_GATE_EF_VEHICLE_LORRY_T = 'CRADLE_TO_GATE_EF_VEHICLE_LORRY_T',
     CRADLE_TO_GATE_EF_VEHICLE_TRACTOR_T = 'CRADLE_TO_GATE_EF_VEHICLE_TRACTOR_T',
     CRADLE_TO_GATE_EF_VEHICLE_VAN_T = 'CRADLE_TO_GATE_EF_VEHICLE_VAN_T',
     CRADLE_TO_GATE_EF_VEHICLE_LORRY_TEU = 'CRADLE_TO_GATE_EF_VEHICLE_LORRY_TEU',
     CRADLE_TO_GATE_EF_VEHICLE_TRACTOR_TEU = 'CRADLE_TO_GATE_EF_VEHICLE_TRACTOR_TEU',
     CRADLE_TO_GATE_EF_VEHICLE_VAN_TEU = 'CRADLE_TO_GATE_EF_VEHICLE_VAN_TEU',
 
     AVERAGE_METHOD_EF_PER_UNIT_OF_MASS_GLASS = 'AVERAGE_METHOD_EF_PER_UNIT_OF_MASS_GLASS',
     AVERAGE_METHOD_EF_PER_UNIT_OF_MASS_ALUMINIUM = 'AVERAGE_METHOD_EF_PER_UNIT_OF_MASS_ALUMINIUM',
     AVERAGE_METHOD_EF_PER_UNIT_OF_MASS_BATTERY = 'AVERAGE_METHOD_EF_PER_UNIT_OF_MASS_BATTERY',
     AVERAGE_METHOD_EF_PER_UNIT_OF_MASS_PRE_PROCESSED_TEA = 'AVERAGE_METHOD_EF_PER_UNIT_OF_MASS_PRE_PROCESSED_TEA',
     AVERAGE_METHOD_EF_PER_UNIT_OF_MASS_THREAD = 'AVERAGE_METHOD_EF_PER_UNIT_OF_MASS_THREAD',
     AVERAGE_METHOD_EF_PER_REFERENCE_UNIT_GLASS = 'AVERAGE_METHOD_EF_PER_REFERENCE_UNIT_GLASS',
     AVERAGE_METHOD_EF_PER_REFERENCE_UNIT_ALUMINIUM = 'AVERAGE_METHOD_EF_PER_REFERENCE_UNIT_ALUMINIUM',
     AVERAGE_METHOD_EF_PER_REFERENCE_UNIT_BATTERY  = 'AVERAGE_METHOD_EF_PER_REFERENCE_UNIT_BATTERY ',
     AVERAGE_METHOD_EF_PER_REFERENCE_UNIT_PRE_PROCESSED_TEA = 'AVERAGE_METHOD_EF_PER_REFERENCE_UNIT_PRE_PROCESSED_TEA',
     AVERAGE_METHOD_EF_PER_REFERENCE_UNIT_THREAD = 'AVERAGE_METHOD_EF_PER_REFERENCE_UNIT_THREAD',
 
     SPEND_BASED_METHOD_EF_STEEL = 'SPEND_BASED_METHOD_EF_STEEL',
     SPEND_BASED_METHOD_EF_ALUMINIUM = 'SPEND_BASED_METHOD_EF_ALUMINIUM',
     SPEND_BASED_METHOD_EF_PET= 'SPEND_BASED_METHOD_EF_PET',
     SPEND_BASED_METHOD_EF_EPOXY_RESIN = 'SPEND_BASED_METHOD_EF_EPOXY_RESIN',
     SPEND_BASED_METHOD_EF_COPPER = 'SPEND_BASED_METHOD_EF_COPPER',
     SPEND_BASED_METHOD_EF_GLASS = 'SPEND_BASED_METHOD_EF_GLASS',
 
 
     //down-stream-transporation
     STORAGE_FACILITY_EF="STORAGE_FACILITY_EF",
     EEIO="EEIO",
     DOWN_ST_TRANS_MODE="DOWN_ST_TRANS_MODE",
 
     //use of sold products
     INTERMEDIATE_EF_THREAD_SYNTHETIC = "INTERMEDIATE_EF_THREAD_SYNTHETIC",
     INTERMEDIATE_EF_PRE_PROCESSED_TEA = "INTERMEDIATE_EF_PRE_PROCESSED_TEA",


     //capital goods
     EMBEDDED_EQUIPMENT_CATEGORY1 ='EMBEDDED_EQUIPMENT_CATEGORY1',
     EMBEDDED_EQUIPMENT_CATEGORY2 = 'EMBEDDED_EQUIPMENT_CATEGORY2',
     EMBEDDED_EQUIPMENT_CATEGORY3 = 'EMBEDDED_EQUIPMENT_CATEGORY3',
     EMBEDDED_MACHINERY_CATEGORY1 = 'EMBEDDED_MACHINERY_CATEGORY1',
     EMBEDDED_MACHINERY_CATEGORY2 = 'EMBEDDED_MACHINERY_CATEGORY2',
     EMBEDDED_MACHINERY_CATEGORY3 = 'EMBEDDED_MACHINERY_CATEGORY3',
 
     EMBEDDED_BUILDINGS_WAREHOUSE = 'EMBEDDED_BUILDINGS_WAREHOUSE',
     EMBEDDED_BUILDINGS_OFFICE = 'EMBEDDED_BUILDINGS_OFFICE',
     EMBEDDED_BUILDINGS_FACTORIESm = 'EMBEDDED_BUILDINGS_FACTORIES',

     EMBEDDED_VEHICLES_PASSENGER_CARS = 'EMBEDDED_VEHICLES_PASSENGER_CARS',
     EMBEDDED_VEHICLES_VANS = 'EMBEDDED_VEHICLES_VANS',
     EMBEDDED_VEHICLES_BUS = 'EMBEDDED_VEHICLES_BUS',
     EMBEDDED_VEHICLES_MOTORCYCLES = 'EMBEDDED_VEHICLES_MOTORCYCLES',
     EMBEDDED_VEHICLES_THREEWHEEL = 'EMBEDDED_VEHICLES_THREEWHEEL',
     EMBEDDED_VEHICLES_TRUCKS = 'EMBEDDED_VEHICLES_TRUCKS',


     //upstram leaded assets (Can you future Es,if has same combination)
     ELECTRICITY = 'ELECTRICITY',
     STEAM = 'STEAM',
     HEATING = 'HEATING',
     COOLING = 'COOLING'

}